enabled: true
messages:
    kick: '&cSorry, this server is unavailable. (Maintenance enabled)'
    motd: '&bServer unavailable.'
    activation: '&cServer will close in 2 minutes (Maintenance)'
    beforemaintenancemotd: ''
activation:
    countdown: 120
    
whitelist:
- md_5
- Notch
- Steve
- Alex
- YourName

serverprotocol: "Maintenance enabled!"
VersionProtocol: true
motdbeforemaintenance: true
ChangeServerIconInMaintenance: false
