enabled: true
messages:
    kick: '&cSorry, this server is unavailable. (Maintenance enabled)'
    motd: '&bServer unavailable.'
    activation: '&cServer entering maintenance mode in {{ TIME }}'
    beforemaintenancemotd: '&a&lWelcome to your server!%newline Have a seat!'
activation:
    countdown: 15
    announce:
    - 15
    - 5
    - 4
    - 3
    - 2
    - 1
whitelist:
- md_5
- Notch
- Steve
- Alex
- YourName

serverprotocol: "Maintenance enabled!"
VersionProtocol: true
motdbeforemaintenance: true
ChangeServerIconInMaintenance: true
