enabled: true
messages:
    kick: '&cSorry, this server is unavailable. (Maintenance enabled)'
    motd: '&bServer unavailable.'
    activation: '&cServer will close in 15 seconds. R'
    beforemaintenancemotd: '&a&lWelcome to your server!%newline Have a seat!'
activation:
    countdown: 120
    announce:
    - 15
    
whitelist:
- md_5
- Notch
- Steve
- Alex
- YourName

serverprotocol: "Maintenance enabled!"
VersionProtocol: true
motdbeforemaintenance: true
ChangeServerIconInMaintenance: false
